CXX = g++
SRCS = main.cpp chara.cpp barb.cpp medu.cpp blueM.cpp hydr.cpp
HEADERS = chara.hpp barb.hpp medu.hpp blueM.hpp hydr.hpp

program1: ${SRCS} ${HEADERS}
	${CXX} ${SRCS} -o program1

clean:
	rm -f *.o program1
