CXX = g++
SRCS = room.cpp exitroom.cpp keyroom.cpp multiroom.cpp normalroom.cpp slideroom.cpp
HEADERS = room.hpp exitroom.hpp keyroom.hpp multiroom.hpp normalroom.hpp slideroom.hpp

program: ${SRCS} ${HEADERS}
	 ${CXX} main.cpp ${SRCS} -o program -g

clean:
	rm -f *.o program


